In [1]:
import pandas as pd
from sentence_transformers import SentenceTransformer, util
from transformers import AutoTokenizer, AutoModel
import faiss
model = SentenceTransformer("cointegrated/rubert-tiny2")

/home/valera/ds_bootcamp/ds-phase-2/10-nlp/myenv_week8/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
df = pd.read_csv("/home/valera/ds_bootcamp/ds-phase-2/11-nn-ext/progect/movies.csv")

In [3]:
embeddings = model.encode(df["description"])
embeddings

array([[ 0.01853042,  0.0322292 ,  0.06703942, ..., -0.02652091,
         0.05015958, -0.09716154],
       [-0.00966859,  0.04808294,  0.0216829 , ..., -0.01079654,
         0.06794685, -0.07415421],
       [ 0.02348504,  0.03505619, -0.00467295, ...,  0.00377644,
        -0.01794447, -0.08194531],
       ...,
       [-0.03674361,  0.02300174,  0.01737977, ...,  0.02999762,
         0.0041385 , -0.12792403],
       [ 0.0619355 ,  0.00993624,  0.04350135, ..., -0.06469355,
         0.01639947, -0.09099746],
       [ 0.02780672,  0.03239826, -0.01327964, ...,  0.03048765,
         0.02394633, -0.00157933]], dtype=float32)

In [4]:
index = faiss.IndexFlatIP(embeddings.shape[1])
index.add(embeddings)


In [5]:
user_input = 'Фильм про пустыни '
user_input = model.encode(user_input)
user_input

array([-4.24255244e-02, -1.82289928e-02, -2.61866748e-02, -2.48654038e-02,
        2.78734472e-02, -1.50490804e-02,  1.46827074e-02,  1.89033411e-02,
       -3.71036083e-02, -1.26234284e-02, -3.07518765e-02,  3.09184659e-02,
        7.39371702e-02, -3.87170874e-02,  9.29381885e-03,  4.16906886e-02,
        7.39737451e-02,  3.45486142e-02,  6.41238643e-03,  4.90722768e-02,
       -1.60454195e-02, -5.30386679e-02,  7.96456262e-03,  2.23097857e-02,
        1.16899446e-01,  4.75437865e-02,  1.90724470e-02,  1.89051665e-02,
       -4.63617556e-02,  4.16701399e-02, -3.25549506e-02, -4.63391133e-02,
        6.72781989e-02, -5.01029864e-02, -1.82559304e-02,  3.55176516e-02,
        1.03392759e-02,  4.32796218e-03, -1.30476311e-01, -1.30972313e-02,
       -8.31011608e-02,  1.13265477e-01, -1.54708633e-02, -1.40870707e-02,
        3.21020000e-02, -2.99318116e-02,  7.26995319e-02, -3.26474495e-02,
        7.65622631e-02, -4.40111049e-02,  1.02419797e-02,  2.57479046e-02,
       -4.34019826e-02, -

In [6]:
user_input = user_input.reshape(1,-1)
user_input

array([[-4.24255244e-02, -1.82289928e-02, -2.61866748e-02,
        -2.48654038e-02,  2.78734472e-02, -1.50490804e-02,
         1.46827074e-02,  1.89033411e-02, -3.71036083e-02,
        -1.26234284e-02, -3.07518765e-02,  3.09184659e-02,
         7.39371702e-02, -3.87170874e-02,  9.29381885e-03,
         4.16906886e-02,  7.39737451e-02,  3.45486142e-02,
         6.41238643e-03,  4.90722768e-02, -1.60454195e-02,
        -5.30386679e-02,  7.96456262e-03,  2.23097857e-02,
         1.16899446e-01,  4.75437865e-02,  1.90724470e-02,
         1.89051665e-02, -4.63617556e-02,  4.16701399e-02,
        -3.25549506e-02, -4.63391133e-02,  6.72781989e-02,
        -5.01029864e-02, -1.82559304e-02,  3.55176516e-02,
         1.03392759e-02,  4.32796218e-03, -1.30476311e-01,
        -1.30972313e-02, -8.31011608e-02,  1.13265477e-01,
        -1.54708633e-02, -1.40870707e-02,  3.21020000e-02,
        -2.99318116e-02,  7.26995319e-02, -3.26474495e-02,
         7.65622631e-02, -4.40111049e-02,  1.02419797e-0

In [7]:
index.search(user_input, 5)





################################### ДАЛЬШЕ НЕ НАДА 

(array([[0.5710056, 0.5706104, 0.5595736, 0.5541355, 0.5538218]],
       dtype=float32),
 array([[1233, 1307, 3218,   86, 4863]]))

In [8]:
util.cos_sim(embeddings , user_input)

tensor([[0.3797],
        [0.4619],
        [0.5027],
        ...,
        [0.3753],
        [0.4772],
        [0.3454]])

In [9]:
model = SentenceTransformer("cointegrated/rubert-tiny2")
df = pd.read_csv("/home/valera/ds_bootcamp/ds-phase-2/11-nn-ext/progect/movies.csv")
embeddings = model.encode(df["description"])
index = faiss.IndexFlatIP(embeddings.shape[1])
user_input = 'Фильм про пустыни '
user_input = model.encode(user_input)
user_input = user_input.reshape(1,-1)
index.search(user_input, 2)
util.cos_sim(embeddings, user_input)

tensor([[0.3797],
        [0.4619],
        [0.5027],
        ...,
        [0.3753],
        [0.4772],
        [0.3454]])

In [10]:
df

page_url  \
0        https://kinogo.uk/9073-deva-i-drakon-2024.html   
1      https://kinogo.uk/6640-kung-fu-panda-4-2024.html   
2              https://kinogo.uk/5783-djuna-2-2023.html   
3     https://kinogo.uk/6185-avatar-poslednij-mag-vo...   
4      https://kinogo.uk/9474-territorija-zla-2024.html   
...                                                 ...   
5478  https://kinogo.uk/12038-po-prozvischu-zver-199...   
5479           https://kinogo.uk/7882-rokki-2-1979.html   
5480  https://kinogo.uk/12034-nepravilnoe-vospitanie...   
5481          https://kinogo.uk/11615-kenzeli-2020.html   
5482  https://kinogo.uk/6999-poslednij-dom-sleva-200...   

                                                img_url  \
0     kinogo.uk//uploads/mini/full/8a/afd93f08b408c6...   
1     kinogo.uk//uploads/mini/full/2c/cb318f7d5965d5...   
2     kinogo.uk//uploads/mini/full/39/269a87642056f7...   
3     kinogo.uk//uploads/mini/full/3d/0738e8230b8eef...   
4     kinogo.uk//uploads/mini/full/1d/6e5e4a96cd7b80...   
...                                                 ...   
5478  kinogo.uk//uploads/mini/full/24/ba19de46677df1...   
5479  kinogo.uk//uploads/mini/full/5b/98a955888509bd...   
5480  kinogo.uk//uploads/mini/full/67/ccc12f91da6500...   
5481  kinogo.uk//uploads/mini/full/44/3314d1c03a6771...   
5482  kinogo.uk//uploads/mini/full/24/9117b83eeb6cc1...   

                               movie_title  \
0                            Дева и дракон   
1                          Кунг-фу Панда 4   
2                       Дюна: Часть вторая   
3       Аватар: Легенда об Аанге (1 сезон)   
4                           Территория зла   
...                                    ...   
5478                ...По прозвищу «Зверь»   
5479                               Рокки 2   
5480  Неправильное воспитание Кэмерон Пост   
5481                               Кензели   
5482                   Последний дом слева   

                                            description   movie_type  \
0     История начинается в мире, где фэнтези сталкив...       Фильмы   
1     "Кунг-фу Панда 4" - это очередная глава в захв...  Мультфильмы   
2     Готовы ли вы отправиться в приключение всей жи...       Фильмы   
3     Добро пожаловать в мир "Аватар: Последний маг ...      Сериалы   
4     В центре нашего рассказа - человек по имени Ри...       Фильмы   
...                                                 ...          ...   
5478  Протагонист этой истории, известный в преступн...       Фильмы   
5479  Рокки Бальбоа, уступивший по очкам в запомнивш...       Фильмы   
5480  Фильм "Неправильное воспитание Кэмерон Пост" п...       Фильмы   
5481  Эта история погружает нас в захватывающее путе...       Фильмы   
5482  Семья из трех человек: мама, папа и дочь, реша...       Фильмы   

                                          genres  year  \
0                 Боевик , Приключения , Фэнтези  2024   
1                                            NaN  2024   
2      Боевик , Драма , Приключения , Фантастика  2023   
3                                            NaN  2024   
4                              Боевик , Криминал  2024   
...                                          ...   ...   
5478                           Боевик , Криминал  1990   
5479                               Драма , Спорт  1979   
5480                             Драма , Комедия  2017   
5481                                  Фантастика  2020   
5482                             Триллер , Ужасы  2009   

                                                 actors  \
0     Милли Бобби Браун, Рэй Уинстон, Анджела Бассет...   
1     Анджелина Джоли, Джеки Чан, Сет Роген, Джек Бл...   
2     Тимоти Шаламе, Ребекка Фергюсон, Зендея, Хавье...   
3     Дэниэл Дэ Ким, Кен Люн, Тэмлин Томита, Пол Ли,...   
4     Рассел Кроу, Майло Вентимилья, Лиам Хемсворт, ...   
...                                                 ...   
5478  Дмитрий Певцов, Татьяна Скороходова, Борис Щер...   
5479  Сильвестр Сталлоне, Карл Уэзерс, Тал

In [11]:
# Загрузить модель и данные
model = SentenceTransformer("cointegrated/rubert-tiny2")

In [12]:
df = pd.read_csv("/home/valera/ds_bootcamp/ds-phase-2/11-nn-ext/progect/movies.csv")


In [13]:
df

page_url  \
0        https://kinogo.uk/9073-deva-i-drakon-2024.html   
1      https://kinogo.uk/6640-kung-fu-panda-4-2024.html   
2              https://kinogo.uk/5783-djuna-2-2023.html   
3     https://kinogo.uk/6185-avatar-poslednij-mag-vo...   
4      https://kinogo.uk/9474-territorija-zla-2024.html   
...                                                 ...   
5478  https://kinogo.uk/12038-po-prozvischu-zver-199...   
5479           https://kinogo.uk/7882-rokki-2-1979.html   
5480  https://kinogo.uk/12034-nepravilnoe-vospitanie...   
5481          https://kinogo.uk/11615-kenzeli-2020.html   
5482  https://kinogo.uk/6999-poslednij-dom-sleva-200...   

                                                img_url  \
0     kinogo.uk//uploads/mini/full/8a/afd93f08b408c6...   
1     kinogo.uk//uploads/mini/full/2c/cb318f7d5965d5...   
2     kinogo.uk//uploads/mini/full/39/269a87642056f7...   
3     kinogo.uk//uploads/mini/full/3d/0738e8230b8eef...   
4     kinogo.uk//uploads/mini/full/1d/6e5e4a96cd7b80...   
...                                                 ...   
5478  kinogo.uk//uploads/mini/full/24/ba19de46677df1...   
5479  kinogo.uk//uploads/mini/full/5b/98a955888509bd...   
5480  kinogo.uk//uploads/mini/full/67/ccc12f91da6500...   
5481  kinogo.uk//uploads/mini/full/44/3314d1c03a6771...   
5482  kinogo.uk//uploads/mini/full/24/9117b83eeb6cc1...   

                               movie_title  \
0                            Дева и дракон   
1                          Кунг-фу Панда 4   
2                       Дюна: Часть вторая   
3       Аватар: Легенда об Аанге (1 сезон)   
4                           Территория зла   
...                                    ...   
5478                ...По прозвищу «Зверь»   
5479                               Рокки 2   
5480  Неправильное воспитание Кэмерон Пост   
5481                               Кензели   
5482                   Последний дом слева   

                                            description   movie_type  \
0     История начинается в мире, где фэнтези сталкив...       Фильмы   
1     "Кунг-фу Панда 4" - это очередная глава в захв...  Мультфильмы   
2     Готовы ли вы отправиться в приключение всей жи...       Фильмы   
3     Добро пожаловать в мир "Аватар: Последний маг ...      Сериалы   
4     В центре нашего рассказа - человек по имени Ри...       Фильмы   
...                                                 ...          ...   
5478  Протагонист этой истории, известный в преступн...       Фильмы   
5479  Рокки Бальбоа, уступивший по очкам в запомнивш...       Фильмы   
5480  Фильм "Неправильное воспитание Кэмерон Пост" п...       Фильмы   
5481  Эта история погружает нас в захватывающее путе...       Фильмы   
5482  Семья из трех человек: мама, папа и дочь, реша...       Фильмы   

                                          genres  year  \
0                 Боевик , Приключения , Фэнтези  2024   
1                                            NaN  2024   
2      Боевик , Драма , Приключения , Фантастика  2023   
3                                            NaN  2024   
4                              Боевик , Криминал  2024   
...                                          ...   ...   
5478                           Боевик , Криминал  1990   
5479                               Драма , Спорт  1979   
5480                             Драма , Комедия  2017   
5481                                  Фантастика  2020   
5482                             Триллер , Ужасы  2009   

                                                 actors  \
0     Милли Бобби Браун, Рэй Уинстон, Анджела Бассет...   
1     Анджелина Джоли, Джеки Чан, Сет Роген, Джек Бл...   
2     Тимоти Шаламе, Ребекка Фергюсон, Зендея, Хавье...   
3     Дэниэл Дэ Ким, Кен Люн, Тэмлин Томита, Пол Ли,...   
4     Рассел Кроу, Майло Вентимилья, Лиам Хемсворт, ...   
...                                                 ...   
5478  Дмитрий Певцов, Татьяна Скороходова, Борис Щер...   
5479  Сильвестр Сталлоне, Карл Уэзерс, Тал

In [14]:
user_input = 'Семья из трех человек: мама, папа и дочь, реша...	'
top_n=5
user_input = model.encode(user_input)
user_input = user_input.reshape(1,-1)
distances, indices = index.search(user_input, top_n)
similar_movies = df.iloc[indices[0]]['movie_title']
list(similar_movies)


['Последний дом слева',
 'Последний дом слева',
 'Последний дом слева',
 'Последний дом слева',
 'Последний дом слева']

In [15]:
distances

array([[-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, -3.4028235e+38,
        -3.4028235e+38]], dtype=float32)

In [16]:


# # Создать вектора для описаний фильмов
# embeddings = model.encode(df["description"])

# # Создать индекс для поиска ближайших соседей
# index = faiss.IndexFlatIP(embeddings.shape[1])
# index.add(embeddings)

# # Функция для поиска фильмов по сходству
# def find_similar_movies(user_input, top_n=5):
#     user_input = model.encode(user_input)
#     user_input = user_input.reshape(1,-1)
#     distances, indices = index.search(user_input, top_n)
#     similar_movies = df.iloc[indices[0]]['description']
#     return list(indices[0])

# # Использование функции
# user_input = 'Фильм про пустыни'
# similar_movies = find_similar_movies(user_input)
# print("Схожие фильмы:", similar_movies)

In [39]:
my_list = ['Боевик', 'Драма']
target_list = ['Боевик', 'Драма', 'Приключения', 'Фантастика']

result = all(elem in target_list for elem in my_list)
print(result)

True


In [49]:
# Список жанров для фильтрации
selected_genres = ['Боевик', 'Драма']

# Создать маску
mask = df['genres'].apply(lambda x: any(genre in x for genre in selected_genres))

# Фильтровать DataFrame
# filtered_df = df[mask]
# filtered_df
mask

TypeError: argument of type 'float' is not iterable

In [51]:

# Пример DataFrame
data = {
    'title': ['Фильм 1', 'Фильм 2', 'Фильм 3', 'Фильм 4'],
    'genres': [['Боевик', 'Драма'], ['Драма', 'Приключения'], ['Комедия'], ['Боевик', 'Приключения', 'Фантастика']]
}
df_test = pd.DataFrame(data)

# Список жанров для фильтрации
selected_genres = ['Боевик', 'Драма']

# Создать маску
mask = df_test['genres'].apply(lambda x: any(genre in x for genre in selected_genres))

# Фильтровать DataFrame
filtered_df = df_test[mask]

In [68]:
test = df['genres'].iloc[0]
test_lst = test.replace(' ', '').split(',')

In [74]:
['Боевик', 'Приключения', 'Фэнтези'] == test_lst

True

In [75]:
test_lst

['Боевик', 'Приключения', 'Фэнтези']